import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Configuración de las fuentes locales
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata global
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav>
            <ul>
              <li><a href="/home">PROBAR CAMARA 2</a></li>
              <li><a href="/about">NOSOSTROS</a></li>
            </ul>
          </nav>
        </header>

        <main>{children}</main>

        <footer>
          <p>© 2024 Tu App. Todos los derechos reservados.</p>
        </footer>
      </body>
    </html>
  );
}
